### ISSUE TITLE
Special Character in the comments cause python to fail running

### ISSUE THREAD

**Issue by rlalance** [matthijskooijman/patchdeps#1]
The letter í in Matías Bordese, inside parser.py cause python to fail running the script.

**Comment by matthijskooijman** [comment]
Hmm, I suspect this might break in python2, python3 probably defaults to utf-8.

Could you see what happens if you add the following line to top of the .py files?

```
# encoding: utf-8
```

If that doesn't help, could you paste the full error?

**Comment by matthijskooijman** [comment]
I'm closing this for lack of response. Feel free to reopen if this is still relevant.
